<?php
$user = $this->_data["_data"];

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit user</title>
  <script src="https://cdn.tailwindcss.com"></script>


</head>
<body>

<section class="bg-gray-900 h-screen">
  <div class="max-w-2xl px-4 py-8 mx-auto lg:py-16">
      <h2 class="mb-4 text-xl font-bold text-white">Edit your profile</h2>
      <form action="/web/userupdate" method="post">
          <div class="grid gap-4 mb-4 sm:grid-cols-2 sm:gap-6 sm:mb-5">
              <div class="sm:col-span-2">
                  <label for="uid" class="block mb-2 text-sm font-medium text-white">Username</label>
                                  
                  <?php
                  
                  if(isset($user['userName'])){
                    $uid = $user['userName'];

                    echo '<input type="text" name="uid" id="uid" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="'.$uid.'" placeholder="Type your username" >';

                  }else{

                    echo '<input type="text" name="uid" id="uid" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="" placeholder="Type your username" >';

                  }

                  ?>

              </div>

              <div class="sm:col-span-2">
                  <label for="email" class="block mb-2 text-sm font-medium text-white">Email</label>
                                  
                  <?php
                  
                  if(isset($user['email'])){
                    $email = $user['email'];

                    echo '<input type="text" name="email" id="email" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="'.$email.'" placeholder="Type your new email" >';

                  }else{

                    echo '<input type="text" name="email" id="email" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="" placeholder="Type your new username" >';

                  }

                  ?>

              </div>

              <div class="sm:col-span-2">
                  <label for="pwd" class="block mb-2 text-sm font-medium text-white">Password</label>
                          
                  <input type="password" name="pwd" id="pwd" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="" placeholder="Type your new password">

              </div>

              <div class="sm:col-span-2">
                  <label for="pwdrepeat" class="block mb-2 text-sm font-medium text-white">Repeat your new password please!</label>
                          
                  <input type="password" name="pwdrepeat" id="pwdrepeat" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="" placeholder="Repeat your new password">

              </div>

              
              <?php
                
                if(!isset($_GET['error'])){
                  
                
                }else{
                
                    $errorCheck = $_GET['error'];
                
                    if($errorCheck == "emotyInputs"){
                
                      echo  '<label for="erro 1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">You have leave some empty fields. Please try again!</label>';   
                   
                    }elseif($errorCheck == "invalidUid"){
                
                      echo  '<label for="erro 1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">You have used some invalid character for the username. Please try again!</label>';   
                   
                    }elseif($errorCheck == "invalidEmail"){
                
                      echo  '<label for="erro 1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">You have used some invalid character for the email. Please try again!</label>';   
                  
                    }elseif($errorCheck == "pwdMatch"){
                
                      echo  '<label for="erro 1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">You password and repeat password does not match. Please try again!</label>';   
                  
                    }elseif($errorCheck == "existingEmail"){
                
                      echo  '<label for="erro 1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">This email it´s already in use. Please login!</label>';   
                    
                    }                
                }
              ?>




          </div>

          <div class="flex items-center mt-20 space-x-[350px]">
            <button type="submit" name="submit" class=" inline-flex items-center border focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center border-white text-white  hover:border-gray-600  hover:text-white hover:bg-gray-600 focus:ring-gay-900">
              <svg class="w-5 h-5 mr-1 -ml-1" fill="currentColor" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6.25 6.375a4.125 4.125 0 118.25 0 4.125 4.125 0 01-8.25 0zM3.25 19.125a7.125 7.125 0 0114.25 0v.003l-.001.119a.75.75 0 01-.363.63 13.067 13.067 0 01-6.761 1.873c-2.472 0-4.786-.684-6.76-1.873a.75.75 0 01-.364-.63l-.001-.122zM19.75 7.5a.75.75 0 00-1.5 0v2.25H16a.75.75 0 000 1.5h2.25v2.25a.75.75 0 001.5 0v-2.25H22a.75.75 0 000-1.5h-2.25V7.5z" clip-rule="evenodd"></path></svg>
              Update your profile
            </button>
            

            <a href="/web/home" type="button" class=" inline-flex items-center border focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center border-white text-white  hover:border-gray-600  hover:text-white hover:bg-gray-600 focus:ring-gay-900">
              <svg class="w-5 h-5 mr-1 -ml-1" fill="currentColor" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd"  d="M6.72 5.66l11.62 11.62A8.25 8.25 0 006.72 5.66zm10.56 12.68L5.66 6.72a8.25 8.25 0 0011.62 11.62zM5.105 5.106c3.807-3.808 9.98-3.808 13.788 0 3.808 3.807 3.808 9.98 0 13.788-3.807 3.808-9.98 3.808-13.788 0-3.808-3.807-3.808-9.98 0-13.788z" clip-rule="evenodd"></path></svg>
              Cancel 
            </a>

          </div>

          <div>

          <div class="flex items-center mt-20 space-x-4">
             
              <a href="/web/userdelete" type="button" class="text-red-600 inline-flex items-center hover:text-white border border-red-600 hover:bg-red-600 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-600 dark:focus:ring-red-900">
                <svg class="w-5 h-5 mr-1 -ml-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path></svg>
                Delete your profile
              </a>

          </div>
      </form>
  </div>
</section>

