<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>


<form action="/web/login" method="post">

  <label for="Login">Login</label><br><br>

  <label for="email">Email:</label><br>

  <?php
  
  if(isset($_GET['email'])){
    $email = $_GET['email'];

    echo '<input type="text" id="email" name="email" value="'.$email.'"><br>';

  }else{

    echo '<input type="text" id="email" name="email" value=""><br>';
  }

  ?>
  
  <label for="password">Password:</label><br>
  <input type="text" id="pwd" name="pwd" value=""><br><br>

  <button type="submit" name="submit">Login</button>

  <?php
  
    if(!isset($_GET['error'])){
      
      

    }else{

        $errorCheck = $_GET['error'];

        if($errorCheck == "notExistingEmail"){

          echo "<p> The email do not its registered. Please sign up!</p>";   

        }elseif($errorCheck == "autentication"){

          echo "<p> Wrong password. Please try again! </p>";

        }
    }
  
  ?>
  </form> 


<form action="/web/register">

  <br>
  <br>
  <br>

<p> If you are not registered click here! ↓↓↓</p>
<button type="submit" name="submit">Sign Up!</button>

  
</form> 


    
</body>
</html>