<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <script src="https://cdn.tailwindcss.com"></script>

  
</head>
<body>

<section class="bg-gray-600">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <a href="#" class="flex items-center mb-20 text-4xl font-semibold text-gray-900">
          <div class="flex space-x-4 mr-6 ">
          <svg class="h-10 w-10 text-gray-900"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M14.5 10c-.83 0-1.5-.67-1.5-1.5v-5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5v5c0 .83-.67 1.5-1.5 1.5z" />  <path d="M20.5 10H19V8.5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5-.67 1.5-1.5 1.5z" />  <path d="M9.5 14c.83 0 1.5.67 1.5 1.5v5c0 .83-.67 1.5-1.5 1.5S8 21.33 8 20.5v-5c0-.83.67-1.5 1.5-1.5z" />  <path d="M3.5 14H5v1.5c0 .83-.67 1.5-1.5 1.5S2 16.33 2 15.5 2.67 14 3.5 14z" />  <path d="M14 14.5c0-.83.67-1.5 1.5-1.5h5c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5h-5c-.83 0-1.5-.67-1.5-1.5z" />  <path d="M15.5 19H14v1.5c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5-.67-1.5-1.5-1.5z" />  <path d="M10 9.5C10 8.67 9.33 8 8.5 8h-5C2.67 8 2 8.67 2 9.5S2.67 11 3.5 11h5c.83 0 1.5-.67 1.5-1.5z" />  <path d="M8.5 5H10V3.5C10 2.67 9.33 2 8.5 2S7 2.67 7 3.5 7.67 5 8.5 5z" /></svg>
          </div>
          TO DO  
      </a>
      <div class="w-full rounded-lg shadow  md:mt-0 sm:max-w-md xl:p-0 bg-gray-900 border-gray-700">
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 class="text-xl font-bold leading-tight tracking-tight text-white md:text-2xl ">
                  Login to your account
              </h1>
              <form class="space-y-4 md:space-y-6" action="/web/login" method="post">
                  <div>
                    <label for="email" class="block mb-2 text-sm font-medium text-white">Email</label>

                      <?php

                      if(isset($_GET['email'])){
                        $email = $_GET['email'];

                        echo '<input type="email" name="email" id="email" value="'.$email.'" class="bg-blue border-2 border-gray-100  sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-00 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-white text-white focus:ring-gray-500 focus:border-blue-500" placeholder=".$email.">';
                 
                      }else{

                        echo '<input type="email" name="email" id="email" class="bg-blue border-2 border-gray-100  sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-white text-white focus:ring-blue-500 focus:border-gray-500"  placeholder="email">';
                      
                      }

                      ?>

                  </div>
                  <div>
                      <label for="pwd" class="block mb-2 text-sm font-medium  text-white">Password</label>
                      <input type="password" name="pwd" id="pwd" placeholder="••••••••" class="bg-blue border-2 border-gray-100  sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-white text-white focus:ring-gray-500 focus:border-gray-500" placeholder="password">
                  </div>

                  <?php
  
                    if(!isset($_GET['error'])){
                      
                      

                    }else{

                        $errorCheck = $_GET['error'];

                        if($errorCheck == "notExistingEmail"){

                          echo  '<label for="erro 1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">The email it is not registered. Please sign up!</label>';   

                        }elseif($errorCheck == "autentication"){

                          echo  '<label for="error 2" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Wrong password. Please try again!</label>';   

                        }
                    }
                  
                  ?>
                  
                  <button type="submit"  name="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Login</button>
                  <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                      Don’t have an account yet? <a href="/web/register" class="font-medium text-primary-500 hover:underline">Sign up</a>
                  </p>
              </form>
          </div>
      </div>
      
  </div>
</section>
  
</body>
</html>