<?php include ROOT_PATH . '/app/views/layouts/header.php'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New task</title>
  <script src="https://cdn.tailwindcss.com"></script>
  

</head>
<body>



<section class="bg-gray-900 h-screen">
  <div class="max-w-2xl px-4 py-8 mx-auto lg:py-16">
      <h2 class="mb-16 text-xl font-bold text-white">Create a new task</h2>
      <form action="/web/taskwrite" method="post">
          <div class="grid gap-4 mb-4 sm:grid-cols-2 sm:gap-6 sm:mb-5">
              <div class="sm:col-span-2">
                  <label for="uid" class="block mb-2 text-sm font-medium text-white">Title</label>
                                  
                  <?php
                  
                  if(isset($_GET['title'])){
                    $title = $_GET['title'];

                    echo '<input type="text" name="title" id="title" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="'.$title.'" placeholder="Type the title of your task" >';

                  }else{

                    echo '<input type="text" name="title" id="title" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="" placeholder="Type the title of your task">';

                  }

                  ?>

              </div>

              <div class="sm:col-span-2">
                  <label for="description" class="block mb-2 text-sm font-medium text-white">Description</label>               
                  <?php
                  
                  if(isset($_GET['description'])){
                    $description = $_GET['description'];

                    echo '<textarea name="description" id="description" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="'.$title.'" placeholder="Write your task description here..."></textarea>';

                  }else{

                    echo '<textarea name="description" id="description" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="" placeholder="Write your task description here..."></textarea>';

                  }

                  ?>

              </div>
              <div class="sm:col-span-2">
                 
              

              <label for="status" class="block mb-2 text-sm font-medium text-white">Select an status</label>

                <?php
  
                  if(isset($_GET['status'])){
                    $status = $_GET['status'];


                    if($status ==  'Started'){

                      echo '<select name="status" id="status" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="">
                                <option value="">--Please choose an option--</option>
                                <option value="Started" selected="selected">Started</option>
                                <option value="In progres">In progres</option>
                                <option value="Done">Done</option>
                            </select>';

                    }elseif($status == "In progres"){

                      echo '<select name="status" id="status" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="">
                                <option value="">--Please choose an option--</option>
                                <option value="Started">Started</option>
                                <option value="In progres" selected="selected">In progres</option>
                                <option value="Done">Done</option>
                            </select>';

                    }elseif($status == "Done"){

                      echo '<select name="status" id="status" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="">
                                <option value="">--Please choose an option--</option>
                                <option value="Started">Started</option>
                                <option value="In progres">In progres</option>
                                <option value="Done" selected="selected">Done</option>
                            </select>';
                    }else{

                      echo '<select name="status" id="status" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="">
                                <option value="">--Please choose an option--</option>
                                <option value="Started">Started</option>
                                <option value="In progres">In progres</option>
                                <option value="Done">Done</option>
                            </select>';
                    }

                  
                  }else{

                    echo '<select name="status" id="status" class=" border  text-sm rounded-lg  block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" value="">
                              <option value="">Please choose an option</option>
                              <option value="Started">Started</option>
                              <option value="In progres">In progres</option>
                              <option value="Done">Done</option>
                          </select>';
                  }

                ?>

              </div>

              
              <div date-rangepicker class="flex items-center">
                <div class="relative">
                <label for="start_date" class="block mb-2 text-sm font-medium text-white">Start date</label>
                  <div class="absolute inset-y-0 left-0 flex items-center pl-3  pointer-events-none">
                      <svg aria-hidden="true" class="w-5 h-5 text-gray-400 mt-7 ml-[128px]" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
                  </div>
                  <input name="start_date" id="start_date" type="date" class=" border  text-sm rounded-lg  block w-full pl-10 p-2.5  bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" placeholder="Select date start">
                </div>
                <span class="mx-4 text-white mt-7 ml-[15px]">to</span>
                <div class="relative">
                <label for="end_date" class="block mb-2 text-sm font-medium text-white">End date</label>
                <div class="absolute inset-y-0 left-0 flex items-center pl-3  pointer-events-none">
                      <svg aria-hidden="true" class="w-5 h-5 text-gray-400 mt-7 ml-[128px]" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
                  </div>
                  <input name="end_date" id="end_date" type="date" class=" border  text-sm rounded-lg  block w-full pl-10 p-2.5  bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" placeholder="Select date start">
                </div>
              </div>

          </div>

          <div class="sm:col-span-1 ">

            <?php
                            
              if(!isset($_GET['error'])){
                
              
              }else{
              
                  $errorCheck = $_GET['error'];
              
                  if($errorCheck == "emotyInputs"){
              
                    echo  '<label for="erro 1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">You have leave some empty fields. Please try again!</label>';   
                
                  }elseif($errorCheck == "wrongOrderDate"){
              
                    echo  '<label for="erro 1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your end date cannot be previous at you startdate. Please try again!</label>';   
            
                  }                         
              }
            ?>

          </div>
          <div class="flex items-center mt-16 space-x-[370px]">
            <button type="submit" name="submit" class=" inline-flex items-center border focus:ring-7 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center border-white text-white  hover:border-gray-600  hover:text-white hover:bg-gray-600 focus:ring-gay-900">
              <svg class="w-5 h-5 mr-1 -ml-1" fill="currentColor" viewBox="0 0 18 18 " xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" clip-rule="evenodd"></path></svg>
              Add a new task
            </button>
            


            

            <a href="/web/home" type="button" class=" inline-flex items-center border focus:ring-7 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center border-white text-white  hover:border-gray-600  hover:text-white hover:bg-gray-600 focus:ring-gay-900">
              <svg class="w-5 h-5 mr-1 -ml-1" fill="currentColor" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd"  d="M6.72 5.66l11.62 11.62A8.25 8.25 0 006.72 5.66zm10.56 12.68L5.66 6.72a8.25 8.25 0 0011.62 11.62zM5.105 5.106c3.807-3.808 9.98-3.808 13.788 0 3.808 3.807 3.808 9.98 0 13.788-3.807 3.808-9.98 3.808-13.788 0-3.808-3.807-3.808-9.98 0-13.788z" clip-rule="evenodd"></path></svg>
              Cancel 
            </a>

          </div>

          
        
      </form>
  </div>
</section>

